### ISSUE TITLE
Use requested protocol in pagination links

### ISSUE THREAD

**Issue by k-nut** [codeforberlin/trees-api-v2#1]
All API responses conveniently come with a `prev` and a `next` prop. Unfortunately, those are always urls starting with `http` even when the original request was made (and served) via `https`. This leads to automated paginated requests breaking in the frontend as non-https requests usually are not allowed on https pages in modern browsers.

The api should therefore check, if a request was made via http or https and send the appropriate strings in the response's pagination strings.

**Comment by jochenklar** [comment]
Fixed using `SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')` and a proper nginx reverse proxy configuration.
